export const formStyles = 'w-full flex flex-col items-center'
export const btnStyles = 'mb-[10px] anim-transit text-[20px] font-roboto bg-[#153b5f] py-[10px] w-[300px] cursor-pointer text-white hover:bg-transparent hover:outline hover:outline-1 hover:outline-[#153b5f] hover:text-[#153b5f] w-full rounded-xl'
export const btnTextStyles = 'font-bold text-[18px] text-[white] leading-[23px]'
export const endTextStyle = 'flex flex-auto items-center justify-center text-[#153b5e] my-4'
export const confirmeFormContainer = 'absolute w-full h-full flex items-center justify-center inset-0 z-10 bg-[#2d2d2d9c]'